name: data_grab
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  flutter_screenutil: ^5.9.3
  grock: ^0.5.7
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.3.1
  dropdown_search: ^5.0.6
  photo_view: ^0.15.0

  # Internal
  flutter_modular: ^6.3.4
  dio: ^5.5.0+1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  excel: ^4.0.6
  intl: ^0.19.0
  easy_mask: ^2.0.1
  flutter_secure_storage: ^9.2.2
  open_filex: ^4.4.0
  file_picker: ^8.0.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  device_info_plus: ^10.1.2

  # DataBase
  path: ^1.9.0
  sqflite: ^2.3.3+1
  synchronized: ^3.1.0+1
  crypto: ^3.0.5

  # Firebase
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_remote_config: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/


flutter_assets_generator:
  path_ignore: [ "assets/fonts" ]
  output_dir: core/generated
