class RaceMap {

  List<Map<String, dynamic>> data () {
    return [
      {"id": 1, "ethnicity": "aikana"},
      {"id": 2, "ethnicity": "aikewara"},
      {"id": 3, "ethnicity": "akunt su"},
      {"id": 4, "ethnicity": "apalai"},
      {"id": 5, "ethnicity": "apurina"},
      {"id": 6, "ethnicity": "arana"},
      {"id": 7, "ethnicity": "arara"},
      {"id": 8, "ethnicity": "aruak"},
      {"id": 9, "ethnicity": "banawa"},
      {"id": 10, "ethnicity": "bara"},
      {"id": 11, "ethnicity": "bare"},
      {"id": 12, "ethnicity": "canela"},
      {"id": 13, "ethnicity": "charrua"},
      {"id": 14, "ethnicity": "desana"},
      {"id": 15, "ethnicity": "guajajara"},
      {"id": 16, "ethnicity": "guarani"},
      {"id": 17, "ethnicity": "hixkaryana"},
      {"id": 18, "ethnicity": "ingariko"},
      {"id": 19, "ethnicity": "jaricuna"},
      {"id": 20, "ethnicity": "kaimbe"},
      {"id": 21, "ethnicity": "kanamari"},
      {"id": 22, "ethnicity": "kapinawa"},
      {"id": 23, "ethnicity": "karipuna"},
      {"id": 24, "ethnicity": "kariri"},
      {"id": 25, "ethnicity": "katukina"},
      {"id": 26, "ethnicity": "kaxinawa"},
      {"id": 27, "ethnicity": "kayapo"},
      {"id": 28, "ethnicity": "kokama"},
      {"id": 29, "ethnicity": "kuruaya"},
      {"id": 30, "ethnicity": "machineri"},
      {"id": 31, "ethnicity": "makurap"},
      {"id": 32, "ethnicity": "makuxi"},
      {"id": 33, "ethnicity": "manairisu"},
      {"id": 34, "ethnicity": "maxakali"},
      {"id": 35, "ethnicity": "munduruku"},
      {"id": 36, "ethnicity": "mura"},
      {"id": 37, "ethnicity": "não respondeu"},
      {"id": 38, "ethnicity": "panara"},
      {"id": 39, "ethnicity": "parintintin"},
      {"id": 40, "ethnicity": "patamona"},
      {"id": 41, "ethnicity": "pataxo"},
      {"id": 42, "ethnicity": "paumari"},
      {"id": 43, "ethnicity": "pianokoto"},
      {"id": 44, "ethnicity": "pira tapuya"},
      {"id": 45, "ethnicity": "satere-mawe"},
      {"id": 46, "ethnicity": "suriana"},
      {"id": 47, "ethnicity": "surui"},
      {"id": 48, "ethnicity": "tariana"},
      {"id": 49, "ethnicity": "taurepang"},
      {"id": 50, "ethnicity": "tikuna"},
      {"id": 51, "ethnicity": "tiriyo"},
      {"id": 52, "ethnicity": "tora"},
      {"id": 53, "ethnicity": "tukano"},
      {"id": 54, "ethnicity": "tupari"},
      {"id": 55, "ethnicity": "tupi-guarani"},
      {"id": 56, "ethnicity": "tupinamba"},
      {"id": 57, "ethnicity": "tuxa"},
      {"id": 58, "ethnicity": "tuyuka"},
      {"id": 59, "ethnicity": "waiapi"},
      {"id": 60, "ethnicity": "waimiri"},
      {"id": 61, "ethnicity": "waiwai"},
      {"id": 62, "ethnicity": "wanana"},
      {"id": 63, "ethnicity": "wapixana"},
      {"id": 64, "ethnicity": "warekena"},
      {"id": 65, "ethnicity": "waura"},
      {"id": 66, "ethnicity": "xikrin"},
      {"id": 67, "ethnicity": "xipaya"},
      {"id": 68, "ethnicity": "yaipiyana"},
      {"id": 69, "ethnicity": "yanomami"},
      {"id": 70, "ethnicity": "yekuana"}
    ];
  }

}
